version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:
  build-library:
    executor:
      name: android/android-machine
      resource-class: xlarge
    steps:
      - checkout
      - run:
          name: Assemble library
          command: ./gradlew scrollableScroll:assemble

  deploy-to-sonatype:
    parameters:
      version:
        type: string
        default: 1.0.13-SNAPSHOT
    executor:
      name: android/android-machine
      resource-class: xlarge
    environment:
      ORG_GRADLE_PROJECT_LIBRARY_VERSION: << parameters.version >>
    steps:
      - checkout
      - run:
          name: Publish to Maven
          command: ./gradlew assemble publishToSonatype closeAndReleaseSonatypeStagingRepository

workflows:
  build-test-deploy:
    jobs:
      - android/run-ui-tests:
          name: build-and-test
          system-image: system-images;android-23;google_apis;x86
          test-command: ./gradlew assemble sample:connectedDebugAndroidTest
          filters:
            tags:
              only: /^[0-9]+.*/
      - hold-for-approval:
          type: approval
          requires:
            - build-and-test
          filters:
            tags:
              only: /^[0-9]+.*/
            branches:
              ignore: /.*/
      - deploy-to-sonatype:
          name: Deploy to Maven Central
          requires:
            - hold-for-approval
          version: $CIRCLE_TAG
          filters:
            tags:
              only: /^[0-9]+.*/s



  nightly-snapshot:
    triggers: #use the triggers key to indicate a scheduled build
      - schedule:
          cron: "0 0 * * *" # use cron syntax to set the schedule
          filters:
            branches:
              only:
                - main
    jobs:
      - android/run-ui-tests:
            name: build-and-test
            system-image: system-images;android-23;google_apis;x86
            test-command: ./gradlew assemblesample:connectedDebugAndroidTest
      - deploy-to-sonatype:
          name: Deploy Snapshot to Sonatype
          version: 1.0.13-SNAPSHOT
          requires:
            - build-and-test
